### ISSUE TITLE
Nested skills

### ISSUE THREAD

**Issue by OctarineSourcerer** [OctarineSourcerer/cyberpunk2020-foundry#32]
Some skills (martial arts, pilot etc) are nested. Display these in skills too, under their parent skill.

**Comment by drowzero0** [comment]
this works in my opinion.
just the view gets stretched a bit.
![image](https://user-images.githubusercontent.com/62395017/114867234-d0776a00-9df4-11eb-9c0f-3ef4d70d26fc.png)

**Comment by OctarineSourcerer** [comment]
Yes, it does stretch a bit, though having things not stretch would start to get into pretty hacky territory. Closing the issue, and if it does end up being more of an issue than I think it is, I'll open an issue about the stretching and see what I can do.
