### ISSUE TITLE
Add encumbrance to armor display

### ISSUE THREAD

**Issue by OctarineSourcerer** [OctarineSourcerer/cyberpunk2020-foundry#33]
At the moment, the armor display shows total stopping powers, but not encumbrance. Maybe with a weight icon between the bottom two segments?

**Comment by drowzero0** [comment]
an Extra weigth indicator would be nice.
i would prefer an extra line below encumbrance.

also encumbrance does not reduce REF atm if there is a stat other than 0 inside.

**Comment by OctarineSourcerer** [comment]
By extra weight indicator, do you mean adding the weight icon and edit box between the bottom two armor segments? Or just a line for adjusting armor weight.

And yes, you're right about the encumbrance not affecting REF at the moment - I'll sort that out. I'm getting to the point where there are enough stat modifiers that I may see about redesigning the stats a little to be able to also show other modifiers affecting them.

**Comment by OctarineSourcerer** [comment]
Encumbrance should now work in a4e4efb. The code was actually there, but it's far too easy in foundry to not be sure whether you should be in Entity, Entity.data, or Entity.data.data to look for things.... So a little change, is sorted now :)

Feel free to still comment on what you mean by extra weight indicator by the way, even though the issue's closed here; it's related.

**Comment by drowzero0** [comment]
encumbrance now gets added correctly. TY.
there is a passage in the rulebook about weights.
![image](https://user-images.githubusercontent.com/62395017/114868534-4f20d700-9df6-11eb-9dd0-000baf53a2c9.png)

in the german version it also references to the body carrying limit at that point.
but i missread that, it doesnt change any stats if you are carrying too much weight.

**Comment by OctarineSourcerer** [comment]
Yes, I don't think there's any explicit mechanical penalty.
