### ISSUE TITLE
idea for initative

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020-foundry#36]
i am actually using your repo for Playing CP2020.
and my way of using the initative is as follows:
    "initiative": "1d10 + @stats.ref.base + @stats.ref.tempMod + @skills.CombatSense.value",

its not a nice way to do it, but it checks for both stats base + modified itself + checks if a solo player has combat sense which counts in for initiave too (at german Core-Ruleset)

**Comment by OctarineSourcerer** [comment]
Oh wow, that's awesome to hear! I hope it's treating you well :)

That's a good way of doing it that doesn't rely on derivative skills, I'll test it out! Cheers for the solo player combat sense tip too, I hadn't realised that, and will add it!

**Comment by drowzero0** [comment]
we made our first full foundry session today with your system. 
the functions that you created work like a charm.
i really love it.
i will keep informing you for other ideas or implementations, if thats is ok for you.

also if its possible. skills.CombatSense.value needs to be used for solos if they do an Awareness Notice check. but guess thats another issue =)

**Comment by OctarineSourcerer** [comment]
Yes, please let me know about any other ideas that come to mind! Happy to imrove this :)
Noted on the combat sense, it's on the list :)

**Comment by OctarineSourcerer** [comment]
The correct initiative roll is now applied in commit 6509b73273d5208ece707f4bdbc1f8f1c7278256 on develop, including combat sense!
Combat Sense should also apply to awareness/notice in 8b521ec82f81b725b155c9932db8041ce3d1d40b 

Enjoy!
