### ISSUE TITLE
stats shown in firefox-browser

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020-foundry#37]
![image](https://user-images.githubusercontent.com/62395017/114303864-86c71080-9ad0-11eb-9666-693aea88b4c6.png)

stats get shown in firefox like this.

to solve this, i added this at line 213 in css/cyberpunk.css

div.stat input[type=number] {
    -moz-appearance:textfield;
}

now even firefox shows the stats correctly

**Comment by OctarineSourcerer** [comment]
Ah! I think I made a commit to solve this yesterday actually - if you pull from develop, see if that works :)

**Comment by drowzero0** [comment]
thanks i will try that.

**Comment by OctarineSourcerer** [comment]
Let me know if it works - if it does, I'll close the issue

**Comment by drowzero0** [comment]
works perfectly! thanks alot
