### ISSUE TITLE
Stats for old sheets -develop_version

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020-foundry#39]
as mentioned before, after changing from dev 1.0.2 to dev 1.0.3 i got a message that every token and actor got updated:
![image](https://user-images.githubusercontent.com/62395017/114617304-428e6880-9ca8-11eb-9000-0ce870b88f03.png)
no errors got shown, a login was possibel the world was startable.

in the charactersheet i noticed some strange STAT.skill dependencies as shown in the screen below.
i made the screenshot AFTER running the console fix:
    let actor = game.actors.get("actor_name");
    actor.skills.skillName.stat = "attr";
left side the existing actor, right side the newly created Actor after updating to 1.0.3
i marked the diffrences, also those which were expected like BODY to BT

![image](https://user-images.githubusercontent.com/62395017/114617871-f4c63000-9ca8-11eb-9528-22f9e1f9b51c.png)

**Comment by drowzero0** [comment]
addition:
rolling the old actor where BT is still BODY drops an error:
![image](https://user-images.githubusercontent.com/62395017/114618362-8cc41980-9ca9-11eb-8ad8-82def7cb5383.png)
rolling in the new actor does not create any error.
same goes for the wrongly as BODY marked skills which should run on EMP
![image](https://user-images.githubusercontent.com/62395017/114618628-db71b380-9ca9-11eb-91f5-a1141065a82c.png)
as a result the old actors cant roll those affected skills from the sheet since no correct stat gets counted in:
(Top is new actor, below old one)
![image](https://user-images.githubusercontent.com/62395017/114618760-08be6180-9caa-11eb-9355-14de9f8132ab.png)

**Comment by OctarineSourcerer** [comment]
Ah okay! That _is_ a weird bug. Let me hand you a fix that should be a little better and should sort both issues for your old actors:
```
let updateData = {};
["HumanPerception","Interview","Leadership","Perform","PersuasionFastTalk","Seduction","Social"].forEach(skillName => updateData[`data.skills.${skillName}.stat`] = "emp");
["StrengthFeat","Swimming", "Endurance"].forEach(skillName => updateData[`data.skills.${skillName}.stat`] = "bt");
let actor = game.actors.getName("boris");
actor.update(updateData);
```

**Comment by OctarineSourcerer** [comment]
I only have custom migration for actors' skills specifically, but I don't think that got properly triggered.

**Comment by drowzero0** [comment]
your Quickfix re-rendered the Actorsheet for Boris and now it gets shown correctly and is rollable again.
do i have to run this for every single character or is it possible to run this for all actor sheets at once?
thanks.

**Comment by OctarineSourcerer** [comment]
> your Quickfix re-rendered the Actorsheet for Boris and now it gets shown correctly and is rollable again.
> do i have to run this for every single character or is it possible to run this for all actor sheets at once?
> thanks.

You don't need to run this for every character anymore even if automatic migration doesn't work (I'm not sure if it does, at the moment). I've made the system-specific migration logic accessible in the most recent commit - just call `game.cyberpunk.migrateWorld()` in the console.

That being said, I don't think it takes into account the emp skills being changed, because that's a bug I haven't gotten to see on my end yet. If you want to do that quickfix for every actor in one go, here's an updated snippet:
```
let updateData = {};
["HumanPerception","Interview","Leadership","Perform","PersuasionFastTalk","Seduction","Social"].forEach(skillName => updateData[`data.skills.${skillName}.stat`] = "emp");
["StrengthFeat","Swimming", "Endurance"].forEach(skillName => updateData[`data.skills.${skillName}.stat`] = "bt");
game.actors.forEach(actor => actor.update(updateData));
```

**Comment by drowzero0** [comment]
Thanks, thats it for this case.

**Comment by OctarineSourcerer** [comment]
Awesome. I'll close this then and have an overarching issue for if automatic migration doesn't work in general: https://github.com/OctarineSourcerer/cyberpunk2020-foundry/issues/47
