### ISSUE TITLE
Rolling on weapons without skills

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020-foundry#41]
Using the Weapon from the charactersheet.combat tab does not take the depending skill into its calculation.
in this case the Actor has the skill "Handgun" at 3
![image](https://user-images.githubusercontent.com/62395017/114656475-742a2280-9cee-11eb-941a-fd00e463568f.png)

**Comment by OctarineSourcerer** [comment]
Weapons should now take skills into account :) Most weapons types can only choose from one skill, but Exotic weapons can choose from any skill either default actors or the owning actors have.

There's only one problem - when weaponType is changed, attackSkill only follows when the sheet is closed - that's being tracked with https://github.com/OctarineSourcerer/cyberpunk2020-foundry/issues/50 though, so consider this one closed.

Btw, the 0 at the end is the Extra Modifiers value the player chooses - I explicitly chose for 0 to still be shown, to make sure the custom modifier is *always* the one at the end of the roll.
