### ISSUE TITLE
Stats and Special-Skills

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020-foundry#43]
The Core-Rulebook shows, that some Role-Skills get added to your STATs.
![image](https://user-images.githubusercontent.com/62395017/114662591-3d0d3e80-9cf9-11eb-9f60-270b746f2562.png)
actually there is no implementation of this for all skills.

Cops get Authority applied to COOL
Rocker get Charismatic Leadership applied  to INT
Solos get CombatSense applied to Initiative (which you already impleneted) and applies to Awareness/Notice
Medias get Credibility applied to INT
Nomads get Family applied to INT
Netrunners get Interface applied to INT
Corporates get Resources applied to INT
Fixers get Streetdeal applied to COOL

Tech and Medtech do not get any bonus by rulebook. 
(as a house-rule i add it to the TECH depending skills, 
Medtech gets Medical Tech applied on Healing/Biology depending Skills from the TECH skills. 
Tech gets Jury Rig applied on techskills with more technical aspects)

**Comment by OctarineSourcerer** [comment]
This is now done, by the rulebook :) There ARE a couple changes to skills though, and so some more added in migration. If you don't see a notification pop up saying "Cyberpunk2020 System Migration to version ${game.system.data.version} completed", I've now made the migration function easily accessible if you need to do it manually - just hit F12, then type in the console `game.cyberpunk.migrateWorld()`

You should see the changes in effect if the special skills with stats (eg authority) say "Special(theirStat)" next to them. Let me know if that works :)

**Comment by drowzero0** [comment]
works as it should, 
2nd and 3rd roll in screen where after updating:
![image](https://user-images.githubusercontent.com/62395017/114704572-0c43fe00-9d27-11eb-834b-8e9afddb7a3c.png)
