### ISSUE TITLE
Cyberware.Items at GEAR tab

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020-foundry#46]
adding diffrent items from TYPE weapon, armor and Misc works perfectly. 
The items get sorted as they should in the GEAR Tab.
![image](https://user-images.githubusercontent.com/62395017/114681071-11e11a00-9d0e-11eb-8d50-2b601146f602.png)

But if i add just one item form TYPE cyberware it seems to drop all formats from items in a category below cyberware:
![image](https://user-images.githubusercontent.com/62395017/114681246-3fc65e80-9d0e-11eb-9ca7-37a2ad772e67.png)

if i delete the cyberware.item it all gets back to how it should look like, as in the first screenshot.

adding 2 items from category cyberware creates the following:
![image](https://user-images.githubusercontent.com/62395017/114681620-9df34180-9d0e-11eb-8d7e-9a0e3aee76a6.png)

**Comment by OctarineSourcerer** [comment]
Nice catch! Fixed in dde5f43, was a mismatched tag. Oops!
